name: create certs

on:
  workflow_run:
    workflows: ["Terraform"]
    types:
      - completed

  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Authenticate to terraform cloud
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      - name: Get data for gcloud auth
        working-directory: infra
        run: |
          terraform init
          export IDENTITY_PROVIDER=$(terraform output -raw "workload_identity_provider")
          echo "::set-env name=IDENTITY_PROVIDER::$IDENTITY_PROVIDER"
          export SERVICE_ACCOUNT=$(terraform output -raw "workload_identity_provider")
          echo "::set-env name=SERVICE_ACCOUNT::$SERVICE_ACCOUNT"


      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0.8.1
        with:
          workload_identity_provider: $IDENTITY_PROVIDER
          service_account: $SERVICE_ACCOUNT
      - name: Test gcloud cli
        run: gcloud version
